#!/bin/bash -v

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

$DIR/bootstrap_steps/xcode-tools.sh
$DIR/bootstrap_steps/softwareupdate.sh
$DIR/bootstrap_steps/homebrew.sh
$DIR/bootstrap_steps/zsh.sh
$DIR/bootstrap_steps/sublime-text3.sh
brew cask install virtualbox
brew cask install vagrant

set +x
echo "######"
echo "###### Unattended install from now on..."
echo "######"
set -x

brew install rbenv ruby-build
$DIR/bootstrap_steps/git-config.sh
$DIR/bootstrap_steps/ssh-keygen.sh
$DIR/bootstrap_steps/desktop-background.sh

brew cask install iterm2
open $DIR/../themes/Solarized\ Light.itermcolors

brew cask install dropbox
open -a Dropbox

brew cask install textexpander
open -a TextExpander

brew cask install alfred
open -a "Alfred 2"

brew install autojump
brew install wget
brew install mtr
brew install ctags
brew install rbenv-ctags
brew cask install sequel-pro
brew cask install skype
brew cask install sourcetree
brew cask install anvil
brew cask install google-chrome
brew cask install marked
brew cask install the-unarchiver
brew cask install atom
