#!/bin/bash -v

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

$DIR/bootstrap_steps/xcode-tools.sh
$DIR/bootstrap_steps/softwareupdate.sh
$DIR/bootstrap_steps/homebrew.sh
$DIR/bootstrap_steps/sublime-text3.sh
brew cask install virtualbox
brew cask install vagrant

set +x
echo "######"
echo "###### Unattended install from now on..."
echo "######"
set -x

brew install rbenv
$DIR/bootstrap_steps/git-config.sh
$DIR/bootstrap_steps/zsh.sh
$DIR/bootstrap_steps/ssh-keygen.sh
$DIR/bootstrap_steps/desktop-background.sh

brew cask install iterm2
open $DIR/../themes/Solarized\ Light.itermcolors

brew install autojump
brew install wget
brew install mtr
brew cask install alfred
brew cask install textexpander
brew cask install dropbox
brew cask install skype
brew cask install sourcetree
brew cask install anvil
brew cask install google-chrome
